//Imports............................................
const { User } = require('../models');


//Seeds............................................
const userdata = [
  { 
    id: 1,
    username: 'kemal',
    email: 'kemal@kemal.com',
    password: 'Admin123',
    firstname: 'Kemal',
    lastname: 'Kanok',
    linkedin: 'kemallinedkin',
    city: 'Ottawa',
    country: 'Canada',
    github: 'kemalkanok',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/kemalkanok/pic-dersi',
    mainprojectname: 'pic-dersi',
    avatar: 'Aang'
  },
  {
    id: 2,
    username: 'mark',
    email: 'mark@mark.com',
    password: 'mark123',
    firstname: 'Mark',
    lastname: 'Dales',
    linkedin: 'marklinedkin',
    city: 'Ottawa',
    country: 'Canada',
    github: 'elipapa',
    experience: 'New Star',
    usermainproject: 'https://github.com/elipapa/markdown-cv',
    mainprojectname: 'markdown-cv',
    avatar: 'Zhao'
  },
  {
    id: 3,
    username: 'sarah',
    email: 'sarah@sarah.com',
    password: 'sarah123',
    firstname: 'Sarah',
    lastname: 'Haras',
    linkedin: 'sarah',
    city: 'Toronto',
    country: 'Canada',
    github: 'oklahomer',
    experience: 'Super Star',
    usermainproject: 'https://github.com/oklahomer/go-sarah',
    mainprojectname: 'go-sarah',
    avatar: 'Katara'
  },
  {
    id: 4,
    username: 'Denis',
    email: 'denis@denis.com',
    password: 'denis123',
    firstname: 'Denis',
    lastname: 'Barushev',
    linkedin: 'denis',
    city: 'Montreal',
    country: 'Canada',
    github: 'denis',
    experience: 'Super Star',
    usermainproject: 'https://github.com/denis/jbuilder',
    mainprojectname: 'jbuilder',
    avatar: 'Hakoda'
  },
  {
    id: 5,
    username: 'kim',
    email: 'kimmy@kimmy.com',
    password: 'kimmy123',
    firstname: 'Kim',
    lastname: 'Altintop',
    linkedin: 'kim',
    city: 'Munich',
    country: 'Germany',
    github: 'kim',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/kim/picky-rs',
    mainprojectname: 'picky-rs',
    avatar: 'Zuko'
  },
  {
    id: 6,
    username: 'tom',
    email: 'tommy@tommy.com',
    password: 'tommy123',
    firstname: 'Tom',
    lastname: 'Malone',
    linkedin: 'tom',
    city: 'Toronto',
    country: 'Canada',
    github: 'tom',
    experience: 'Super Star',
    usermainproject: 'https://github.com/tom/node-deploy-app',
    mainprojectname: 'node-deploy-app',
    avatar: 'Ozai'
  },
  {
    id: 7,
    username: 'stephanie',
    email: 'stephanie@stephanie.com',
    password: 'stephanie123',
    firstname: 'Stephanie',
    lastname: 'Siaw',
    linkedin: 'stephanie',
    city: 'Toronto',
    country: 'Canada',
    github: 'stephanie',
    experience: 'Super Star',
    usermainproject: 'https://github.com/stephanie/travel-bot',
    mainprojectname: 'travel-bot',
    avatar: 'Katara'
  },
  {
    id: 8,
    username: 'mleech101',
    email: 'mandyleech101@gmail.com',
    password: 'Mandy123',
    firstname: 'Mandy',
    lastname: 'Leech',
    linkedin: 'leech001',
    city: 'Fredrickton',
    country: 'Canada',
    github: 'leech001',
    experience: 'New Star',
    usermainproject: 'https://github.com/leech001/RF-BARRIER',
    mainprojectname: 'RF-BARRIER',
    avatar: 'Katara'
  },
  {
    id: 9,
    username: 'bbartfeenstra',
    email: 'bbartfeenstra@gmail.com',
    password: 'Betty123',
    firstname: 'Betty',
    lastname: 'Bartfeenstra',
    linkedin: 'bbartfeenstra001',
    city: 'Ottawa',
    country: 'Canada',
    github: 'gramps-project',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/gramps-project/gramps',
    mainprojectname: 'gramps',
    avatar: 'Katara'
   },
  {
    id: 10,
    username: 'HamkerCat',
    email: 'TheHamkerCat@gmail.com',
    password: 'Dave123',
    firstname: 'David',
    lastname: 'Winstra',
    linkedin: 'HamkerCat',
    city: 'Vancover',
    country: 'Canada',
    github: 'TheHamkerCat',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/TheHamkerCat/WilliamButcherBot',
    mainprojectname: 'WilliamButcherBot',
    avatar: 'Ozai'
  },
  {
    id: 11,
    username: 'psandford',
    email: 'psanford11@gmail.com',
    password: 'Pete123',
    firstname: 'Peter',
    lastname: 'Sanford',
    linkedin: 'psanfond11',
    city: 'Toronto',
    country: 'Canada',
    github: 'psanford',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/psanford',
    mainprojectname: 'wormhole-william',
    avatar: 'Sokka'
  },
  {
    id: 12,
    username: 'WillyR',
    email: 'WillyRedlin101@gmail.com',
    password: 'Willy123',
    firstname: 'Willy',
    lastname: 'Redlin',
    linkedin: 'WillyRedlin',
    city: 'Winnipeg',
    country: 'Canada',
    github: 'whiteblock',
    experience: 'Super Star',
    usermainproject: 'https://github.com/whiteblock',
    mainprojectname: 'hobbits',
    avatar: 'Hakoda'
  },
  {
    id: 13,
    username: 'BrucePeterson',
    email: 'BrucePeterson1@gmail.com',
    password: 'WBPete123',
    firstname: 'Bruce',
    lastname: 'Peterson',
    linkedin: 'BrucePeterson',
    city: 'Winnipeg',
    country: 'Canada',
    github: 'dice-group',
    experience: 'Super Star',
    usermainproject: 'https://github.com/dice-group',
    mainprojectname: 'orca',
    avatar: 'Ozai'
  },
  {
    id: 14,
    username: 'VernonGrant',
    email: 'VernonGrant10@gmail.com',
    password: 'vern123',
    firstname: 'Vernon',
    lastname: 'Grant',
    linkedin: 'VernonGrant10',
    city: 'Calgary',
    country: 'Canada',
    github: 'VernonGrant',
    experience: 'New Star',
    usermainproject: 'https://github.com/VernonGrant',
    mainprojectname: 'VernonGrant',
    avatar: 'Zhao'
  },
  {
    id: 15,
    username: 'JaniePowers',
    email: 'JaniePower33@gmail.com',
    password: 'J123',
    firstname: 'Janie',
    lastname: 'Powers',
    linkedin: 'JaniePower33',
    city: 'Edmonton',
    country: 'Canada',
    github: 'seemoo-lab',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/seemoo-lab',
    mainprojectname: 'frankenstein',
    avatar: 'Aang'
  },
  {
    id: 16,
    username: 'ClaireGib',
    email: 'ClaireGison@gmail.com',
    password: 'Claire123',
    firstname: 'Claire',
    lastname: 'Gibson',
    linkedin: 'ClaireGibson2',
    city: 'Red Deer',
    country: 'Canada',
    github: 'txthinking',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/txthinking',
    mainprojectname: 'frank',
    avatar: 'Katara'
  },
  {
    id: 17,
    username: 'WestonBoothe',
    email: 'WestonBoothe1@gmail.com',
    password: 'West123',
    firstname: 'Weston',
    lastname: 'Boothe',
    linkedin: 'WestonBoothe',
    city: 'Ajax',
    country: 'Canada',
    github: 'matter-labs-archive',
    experience: 'Bright Star',
    usermainproject: 'https://github.com/matter-labs-archive',
    mainprojectname: 'FranklinPay-iOS',
    avatar: 'Iroh'
  },
  {
    id: 18,
    username: 'NancyMonk',
    email: 'NancyMonk@gmail.com',
    password: 'Nancy123',
    firstname: 'Nancy',
    lastname: 'Monk',
    linkedin: 'NancyMonk',
    city: 'Kingston',
    country: 'Canada',
    github: 'NancyFx',
    experience: 'New Star',
    usermainproject: 'https://github.com/NancyFx',
    mainprojectname: 'Nancy',
    avatar: 'Sokka'
  },
  {
    id: 19,
    username: 'CathyWong',
    email: 'CathyWong@gmail.com',
    password: 'Cathy123',
    firstname: 'Cathy',
    lastname: 'Wong',
    linkedin: 'CathyWong',
    city: 'Ottawa',
    country: 'Canada',
    github: 'catcherwong',
    experience: 'New Star',
    usermainproject: 'https://github.com/catcherwong',
    mainprojectname: 'Demos',
    avatar: 'Suki'
  },
  {
    id: 20,
    username: 'GeneCarter',
    email: 'GeneCarter34@gmail.com',
    password: 'Gene123',
    firstname: 'Gene',
    lastname: 'Carter',
    linkedin: 'GeneCarter34',
    city: 'Quebec City',
    country: 'Canada',
    github: 'CarterCommunity',
    experience: 'New Star',
    usermainproject: 'https://github.com/CarterCommunity',
    mainprojectname: 'Carter',
    avatar: 'Zhao'
  },
];


//Init............................................
const seedUsers = () => User.bulkCreate(userdata);


//Exports............................................
module.exports = seedUsers;
